steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/abstract-water-467718-e7/hackrx-repo/intelligent-doc-system:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/abstract-water-467718-e7/hackrx-repo/intelligent-doc-system:latest'
